apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: guestbook
